swagger: '2.0'
info:
  title: 'Coding Statistics Stream API'
  description: 'Statistic Data from the Coding Solution. The events are generated after every coding operation, currently only for video coding. The data is crucial for querying and analysis in AWS Athena by DWH LS OPS.'
  contact:
    name: erkennen.codieren.pakete@post.ch
  version: 0.2.0-feature-initial-api-setup.5
host: 'server:8080'
basePath: Kafka
paths:
  logistics.coding.statistics.Mailpiece-event:
    get:
      summary: 'Kafka Topic for sending coding statistics data'
      description: 'All the related coding statistics data'
      tags:
        - logistics.coding.statistics
      responses:
        '200':
          description: 'The event which occured'
          schema: {type: array, $ref: 'CodedStatisticEvents'}
definitions:
  ActivityType:
    type: string
    enum:
      - CONNECTOR_PLATFORM
      - PRIORITIZER
      - GET_PRIORITIZER
      - CODING_CLIENT
      - BUFFER_CODING_CLIENT
      - DISPLAYED_CODING_CLIENT
      - CONVERT_IMAGE
      - TRANSFER
      - PLATTFORM_SDSC
      - CODING_REQUEST
      - WAITING
    description: "CONNECTOR_PLATFORM       The coding task is received in the connector and forwarded to the platform.\nPRIORITIZER              The coding task lives in the prioritizer/queue.\nGET_PRIORITIZER          The coding task gets requested and returned to the prioritizer/queue.\nCODING_CLIENT            The coding task is at the coding client.\nBUFFER_CODING_CLIENT     The coding task is buffered in the coding client.\nDISPLAYED_CODING_CLIENT  The coding task is displayed in the coding client.\nCONVERT_IMAGE            The images gets converted.\nTRANSFER                 The transfer of the the coding task and result between the coding client and the platform.\nPLATTFORM_SDSC           The coding task is received in the platform and forwarded to the Sorting Decision System Configurator.\nCODING_REQUEST           The coding task lives in the platform.\nWAITING                  The coder was experiencing a grey waiting screen before it could code this task."
  CodedExternalCarrierId:
    type: object
    properties:
      mailpieceId:
        type: string
        description: 'Identifier of the mailpiece from the external carrier.'
      type:
        $ref: 'ExternalCarrierType'
        description: 'Type of the external carrier id.'
    required:
      - mailpieceId
      - type
    additionalProperties: false
    description: 'Mailpiece identifier of external carrier. Contains the identifier and the type of the external carrier id.'
  DateTime:
    type: string
    description: "<a href=\"https://swagger.io/docs/specification/data-models/data-types/#string\">String @format date-time</a>,\nas defined by <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6</a>,\nfor example: <code>2014-05-22T10:42:42.542+00:00</code>."
    format: date-time
  Int:
    type: integer
    description: '<a href="https://swagger.io/docs/specification/data-models/data-types/#numbers">Number @asType integer</a>'
  CodedStatisticEvents:
    type: object
    properties:
      eventId:
        type: string
        description: "Unique identifier of a coding message.\nPrimary key 🔑"
        maxLength: 200
      timestamp:
        $ref: 'DateTime'
        description: 'Time when the event is published.'
      processingItemId:
        type: string
        description: "Identifier generated by the sorting unit for one sorting cycle. This id is only valid during the\nsorting cycle and might be reused by the sorting unit quickly for a next sorting cycle.\nTo correlate event to one sorting cycle use the sortingCycleId."
      mailpieceGlobalKey:
        type: string
        description: "Globally unique key for the mailpiece.\nOnly a single mailpiece may have the same Key and the Key is never to be reused again, allowing to identify every mailpiece\never processed.\nPrimary key 🔑"
      idTags:
        $ref: 'IdentifierTags'
        description: 'Contains a list of ids identifying the processing item.'
      source:
        $ref: 'EventSource'
        description: 'The system which publishes the event.'
      video:
        $ref: 'VideoEvents'
        description: 'Mailpiece has been coded during the sorting process by video mailpice coding (VMC).'
    required:
      - eventId
      - timestamp
      - processingItemId
      - mailpieceGlobalKey
      - source
      - video
    additionalProperties: false
  CodingEventProducer:
    type: string
    enum:
      - VIDEO_CODING
      - MANUAL_CODING_REJECT
      - MANUAL_CODING_BULK
      - MANUAL_CODING_BULK_SCANNING
      - AUTOMATIC_CODING
    description: "VIDEO_CODING                 Component where information is remotely captured or entered by a coder based on an image (SPS Vietnam / other).\nMANUAL_CODING_REJECT         Component where barcodes, weight, dimensions and address information are captured or entered (manually) (MMC).\nMANUAL_CODING_BULK           Component where barcodes, weight, dimensions and address information for bulky goods are captured or entered (manually or partially automated) (MMCB).\nMANUAL_CODING_BULK_SCANNING  Component where a coder manually captures barcodes and other specific information for bulky goods (MMCBS).\nAUTOMATIC_CODING             Automatic coding system using optical character recognition (OCR)."
  EventSource:
    type: object
    properties:
      producer:
        $ref: 'CodingEventProducer'
        description: 'Device which provided the information.'
      instance:
        type: string
        description: 'Instance of the device.'
    required:
      - producer
      - instance
    additionalProperties: false
    description: "Describes which system provided the information. This is meant to be used for diagnositcs\nand should not be used to infer any business cases."
  ExternalCarrierType:
    type: string
    enum:
      - FEDEX
  IdentifierTags:
    type: object
    properties:
      nationalMailpieceIds:
        type: array
        items:
          type: string
        description: "Contains the list of national identifiers to track a mail item within the country.\nThe id is printed on the mailpiece by the sender."
      internationalMailpieceIds:
        type: array
        items:
          type: string
        description: "Contains the list of international identifiers to track a mail item internationally.\nThe id is printed on the mailpiece by the sender."
      customsNumbers:
        type: array
        items:
          type: string
        description: 'Contains the list of national identifiers from the customs to track an imported mail item within the country.'
      boxIds:
        type: array
        items:
          type: string
        description: 'Contains the list of identifiers to track a Dispobox within the country.'
      letterTrackingIds:
        type: array
        items:
          type: string
        description: 'Contains the list of identifiers to track mix mail with a data matrix code (DMC80).'
      externalCarrierIds:
        type: array
        items:
          $ref: 'CodedExternalCarrierId'
        description: 'Contains the list of identifier and type from external carriers like Fedex.'
    additionalProperties: false
    description: 'Contains a list of logistic or technical identifiers to track a mail item within a specific context.'
  SortingUnit:
    type: object
    properties:
      sortingUnitKey:
        type: string
        description: 'Unique identifier of the sorting unit at a specific location.'
      locationKey:
        type: string
        description: 'Unique key identifying the location.'
    required:
      - sortingUnitKey
      - locationKey
    additionalProperties: false
    description: 'Sorting unit at a location performing the sorting process step.'
  TimeToLifeType:
    type: string
    enum:
      - TIME_1
      - TIME_2
      - TIME_3
      - WEIGHT_1
      - WEIGHT_2
      - WEIGHT_3
    description: "TIME_1    The first maximum time, in milliseconds, the coding task is supposed to take before it is coded. If the platform cannot code the item within this\ntime, it will use TIME_2 to as a new timeout.\nTIME_2    The second maximum time, in milliseconds, the coding task is supposed to take before it is coded. If the platform cannot code the item within this\ntime, it will use TIME_3 to as a new timeout.\nTIME_3    The third maximum time, in milliseconds, the coding task is supposed to take before it is coded.\nWEIGHT_1  The priority given to the first maximum time (TIME_1) to define how long the coding task is supposed to take before it is coded.\nWEIGHT_2  The priority given to the second maximum time (TIME_2) to define how long the coding task is supposed to take before it is coded.\nWEIGHT_3  The priority given to the third maximum time (TIME_3) to define how long the coding task is supposed to take before it is coded."
  VideoActivity:
    type: object
    properties:
      type:
        $ref: 'ActivityType'
        description: 'Type of activity the coder or the platform performs.'
      duration:
        $ref: 'Int'
        description: 'Duration of the activity in miliseconds.'
    required:
      - type
      - duration
    additionalProperties: false
  VideoCodingResultType:
    type: string
    enum:
      - ACCEPT
      - REJECT_TIMEOUT
      - REJECT_TECHNICAL
    description: "ACCEPT            Task is accepted and processed successfully.\nREJECT_TIMEOUT    Reject due to a timeout. In this case the video coding plattform doesn't deliver a result within a specific time.\nREJECT_TECHNICAL  Reject due to technical problems (e.g. black images, poor resolution, blurred images, only partial image build up)."
  VideoCodingResult:
    type: object
    properties:
      codingTask:
        $ref: 'VideoCodingTask'
        description: "The coding task being performed within the video coding system.\nIt categorizes the task by its operational context (internal or external) and the type of data processing involved (region, postcode or address)."
      codingTaskType:
        $ref: 'VideoCodingTaskType'
        description: 'The type of the coding task which determines the nature of the coding task to be performed in the video coding process.'
      codingResultType:
        $ref: 'VideoCodingResultType'
        description: 'The coding result type which indicates the outcome of the coding task.'
      activities:
        type: array
        items:
          $ref: 'VideoActivity'
        description: 'Activities the coder or the platforms performs during a coding task and the duration of the activity.'
      timeToLife:
        type: array
        items:
          $ref: 'VideoTimeToLife'
        description: 'The maximum time, in milliseconds, the coding task is supposed to take before it is coded.'
      keystrokes:
        type: string
        description: 'The keystrokes entered by the coder to code the coding task.'
    required:
      - codingTask
      - codingTaskType
      - codingResultType
      - keystrokes
    additionalProperties: false
    description: 'Information captured by the coding systems during coding'
  VideoCodingTaskType:
    type: string
    enum:
      - OPERATIONAL
      - QUALITY
      - TRAINING
      - EXAM
    description: "OPERATIONAL   Coding tasks are tasks provided in the production Coding Task Menu in the Webcoding Portal. They are generated by either the Mail Matching System or a simulator.\nQUALITY       Quality tasks are generated by the Video Coding System. Depending on the settings every nth coding tasks is duplicated and added to the coding queue as a quality task. The result of the coding task and the quality task can then be compared in the Quality Viewer of the Webcoding Dashboard.\nTRAINING      Training tasks provided in the Training Module in the Video Coding System, based on the selected training set.\nEXAM          Exam tasks provided in the Exam module in the Video Coding System, based on the selected exam set."
  VideoCodingTask:
    type: string
    enum:
      - INTERNAL_REGION
      - INTERNAL_POSTCODE
      - INTERNAL_ADDRESS
      - EXTERNAL_REGION
      - EXTERNAL_POSTCODE
      - EXTERNAL_ADDRESS
    description: "INTERNAL_REGION    Component VCS CH: Task in the video coding system where the coder detects address region of interest (ROI) elements on an image.\nINTERNAL_POSTCODE  Component VCS CH: Task in the video coding system where the coder enters the postcode based on an address region of interest (ROI) image.\nINTERNAL_ADDRESS   Component VCS CH: Task in the video coding system where the coder enters the recipient address based on an address region of interest (ROI) image.\nEXTERNAL_REGION    Component VCS Offshore: Task in the video coding system where the coder detects address region of interest (ROI) elements on an image.\nEXTERNAL_POSTCODE  Component VCS Offshore: Task in the video coding system where the coder enters the postcode based on an address region of interest (ROI) image.\nEXTERNAL_ADDRESS   Component VCS Offshore: Task in the video coding system where the coder enters the recipient address based on an address region of interest (ROI) image."
  VideoEvents:
    type: object
    properties:
      sortingUnit:
        $ref: 'SortingUnit'
        description: 'Sorting unit where the mailpiece was being processed.'
      serviceProvider:
        $ref: 'VideoServiceProvider'
        description: 'Service provider which coded the coding task.'
      codingResult:
        $ref: 'VideoCodingResult'
        description: 'Contains the coding results per coding task.'
    required:
      - sortingUnit
      - serviceProvider
    additionalProperties: false
  VideoServiceProvider:
    type: object
    properties:
      name:
        type: string
        description: 'The name of the service provider which coded the coding task (e.g. SPS Vietnam).'
      location:
        type: string
        description: 'The name of the service provider location which coded the coding task.'
    required:
      - name
      - location
    additionalProperties: false
  VideoTimeToLife:
    type: object
    properties:
      type:
        $ref: 'TimeToLifeType'
        description: "The maximum time and its priority define how long the coding task is supposed to take before it is coded.\nIf this information is not recieved, the Video Coding System will load the default setting."
      duration:
        $ref: 'Int'
        description: 'Amount of time in miliseconds.'
    required:
      - type
      - duration
    additionalProperties: false
