swagger: '2.0'
info:
  title: 'Coding Statistics Stream API'
  description: 'Statistic Data from the new Coding Solution'
  contact:
    name: erkennen.codieren.pakete@post.ch
  version: 0.2.0-feature-initial-api-setup.3
host: 'server:8080'
basePath: Kafka
paths:
  logistics.coding.statistics.Mailpiece-event:
    get:
      summary: 'Kafka Topic for sending coding statistics data'
      description: 'All the related coding statistics data'
      tags:
        - logistics.coding.statistics
      responses:
        '200':
          description: 'The event which occured'
          schema: {type: array, $ref: 'CodedStatisticEvents'}
definitions:
  ActivityType:
    type: string
    enum:
      - CONNECTOR_PLATFORM
      - PRIORITIZER
      - GET_PRIORITIZER
      - CODING_CLIENT
      - BUFFER_CODING_CLIENT
      - DISPLAYED_CODING_CLIENT
      - CONVERT_IMAGE
      - TRANSFER
      - PLATTFORM_SDSC
      - CODING_REQUEST
      - WAITING
    description: "CONNECTOR_PLATFORM       The coding request is received in the connector and forwarded to the WNG platform.\nPRIORITIZER              The coding request lives in the prioritizer/queue.\nGET_PRIORITIZER          The coding request gets requested and returned to the prioritizer/queue.\nCODING_CLIENT            The coding request is at the coding client.\nBUFFER_CODING_CLIENT     The coding request is buffered in the coding client.\nDISPLAYED_CODING_CLIENT  The coding request is displayed in the coding client.\nCONVERT_IMAGE            The images gets converted.\nTRANSFER                 The Transfer of the the coding request and result between the coding client and the WNG platform.\nPLATTFORM_SDSC           The coding result is received in the WNG platform and forwarded to the SDSC.\nCODING_REQUEST           The coding request lives in the WNG platform.\nWAITING                  The coder was experiencing a grey waiting screen before it could code this request."
  CodedExternalCarrierId:
    type: object
    properties:
      mailpieceId:
        type: string
        description: 'Identifier of the mailpiece from the external carrier.'
      type:
        $ref: 'ExternalCarrierType'
        description: 'Type of the external carrier id.'
    required:
      - mailpieceId
      - type
    additionalProperties: false
    description: 'Mailpiece identifier of external carrier. Contains the identifier and the type of the external carrier id.'
  CodedSortingUnit:
    type: object
    properties:
      sortingUnitKey:
        type: string
        description: 'Unique identifier of the sorting unit at a specific location.'
      locationKey:
        type: string
        description: 'Unique key identifying the location.'
    required:
      - sortingUnitKey
      - locationKey
    additionalProperties: false
    description: 'Sorting unit at a location performing the sorting process step.'
  DateTime:
    type: string
    description: "<a href=\"https://swagger.io/docs/specification/data-models/data-types/#string\">String @format date-time</a>,\nas defined by <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6</a>,\nfor example: <code>2014-05-22T10:42:42.542+00:00</code>."
    format: date-time
  Int:
    type: integer
    description: '<a href="https://swagger.io/docs/specification/data-models/data-types/#numbers">Number @asType integer</a>'
  CodedStatisticEvents:
    type: object
    properties:
      eventId:
        type: string
        description: "Unique identifier of a coding message.\nPrimary key 🔑"
        maxLength: 200
      timestamp:
        $ref: 'DateTime'
        description: 'Time when the event is published.'
      processingItemId:
        type: string
        description: "Identifier generated by the sorting unit for one sorting cycle. This id is only valid during the\nsorting cycle and might be reused by the sorting unit quickly for a next sorting cycle.\nTo correlate event to one sorting cycle use the sortingCycleId."
      mailpieceGlobalKey:
        type: string
        description: "Globally unique key for the mailpiece.\nOnly a single mailpiece may have the same Key and the Key is never to be reused again, allowing to identify every mailpiece\never processed.\nPrimary key 🔑"
      idTags:
        $ref: 'IdentifierTags'
        description: 'Contains a list of ids identifying the processing item.'
      source:
        $ref: 'EventSource'
        description: 'The system which publishes the event.'
      video:
        $ref: 'VideoEvents'
        description: 'Mailpiece has been coded during the sorting process by video mailpice coding (VMC).'
    required:
      - eventId
      - timestamp
      - processingItemId
      - mailpieceGlobalKey
      - source
      - video
    additionalProperties: false
  CodingEventProducer:
    type: string
    enum:
      - VIDEO_CODING
      - MANUAL_CODING_REJECT
      - MANUAL_CODING_BULK
      - MANUAL_CODING_BULK_SCANNING
      - AUTOMATIC_CODING
    description: "VIDEO_CODING                 Component where information is remotely captured or entered by a coder based on an image (SPS Vietnam / other).\nMANUAL_CODING_REJECT         Component where barcodes, weight, dimensions and address information are captured or entered (manually) (MMC).\nMANUAL_CODING_BULK           Component where barcodes, weight, dimensions and address information for bulky goods are captured or entered (manually or partially automated) (MMCB).\nMANUAL_CODING_BULK_SCANNING  Component where a coder manually captures barcodes and other specific information for bulky goods (MMCBS).\nAUTOMATIC_CODING             Automatic coding system using optical character recognition (OCR)."
  EventSource:
    type: object
    properties:
      producer:
        $ref: 'CodingEventProducer'
        description: 'Device which provided the information.'
      instance:
        type: string
        description: 'Instance of the device.'
    required:
      - producer
      - instance
    additionalProperties: false
    description: "Describes which system provided the information. This is meant to be used for diagnositcs\nand should not be used to infer any business cases."
  ExternalCarrierType:
    type: string
    enum:
      - FEDEX
  IdentifierTags:
    type: object
    properties:
      nationalMailpieceIds:
        type: array
        items:
          type: string
        description: "Contains the list of national identifiers to track a mail item within the country.\nThe id is printed on the mailpiece by the sender."
      internationalMailpieceIds:
        type: array
        items:
          type: string
        description: "Contains the list of international identifiers to track a mail item internationally.\nThe id is printed on the mailpiece by the sender."
      customsNumbers:
        type: array
        items:
          type: string
        description: 'Contains the list of national identifiers from the customs to track an imported mail item within the country.'
      boxIds:
        type: array
        items:
          type: string
        description: 'Contains the list of identifiers to track a Dispobox within the country.'
      letterTrackingIds:
        type: array
        items:
          type: string
        description: 'Contains the list of identifiers to track mix mail with a data matrix code (DMC80).'
      externalCarrierIds:
        type: array
        items:
          $ref: 'CodedExternalCarrierId'
        description: 'Contains the list of identifier and type from external carriers like Fedex.'
    additionalProperties: false
    description: 'Contains a list of logistic or technical identifiers to track a mail item within a specific context.'
  TimeToLifeType:
    type: string
    enum:
      - TIME_1
      - TIME_2
      - TIME_3
      - WEIGHT_1
      - WEIGHT_2
      - WEIGHT_3
    description: "TIME_1    The first maximum time, in milliseconds, the coding request is supposed to take before it is coded. If the platform cannot code the item within this\ntime, it will use TIME_2 to as a new timeout.\nTIME_2    The second maximum time, in milliseconds, the coding request is supposed to take before it is coded. If the platform cannot code the item within this\ntime, it will use TIME_3 to as a new timeout.\nTIME_3    The third maximum time, in milliseconds, the coding request is supposed to take before it is coded.\nWEIGHT_1  The priority given to the first maximum time (TIME_1) to define how long the coding request is supposed to take before it is coded.\nWEIGHT_2  The priority given to the second maximum time (TIME_2) to define how long the coding request is supposed to take before it is coded.\nWEIGHT_3  The priority given to the third maximum time (TIME_3) to define how long the coding request is supposed to take before it is coded."
  VideoCodedActivity:
    type: object
    properties:
      type:
        $ref: 'ActivityType'
        description: 'Type of Activity the Coder or the Platform performs.'
      duration:
        $ref: 'Int'
        description: 'Duration of the activity in miliseconds.'
    required:
      - type
      - duration
    additionalProperties: false
  VideoCodedCodingRequestType:
    type: string
    enum:
      - OPERATIONAL
      - QUALITY
      - TRAINING
      - EXAM
    description: "OPERATIONAL   Coding Requests related to operational procedures\nQUALITY       Coding Requests focused on quality control and assurance\nTRAINING      Coding Requests for training and educational purposes\nEXAM          Coding Requests for examination and assessment"
  VideoCodedCodingResultType:
    type: string
    enum:
      - ACCEPT
      - REJECT_TIMEOUT
      - REJECT_TECHNICAL
    description: "ACCEPT            Task is accepted and processed successfully.\nREJECT_TIMEOUT    Reject due to a timeout. In this case the solution doesn't deliver a result within a specific time.\nREJECT_TECHNICAL  Reject due to technical problems (e.g. black images, poor resolution, blurred images, only partial image build up)."
  VideoCodedCodingTask:
    type: string
    enum:
      - INTERNAL_REGION
      - INTERNAL_POSTCODE
      - INTERNAL_ADDRESS
      - EXTERNAL_REGION
      - EXTERNAL_POSTCODE
      - EXTERNAL_ADDRESS
    description: "INTERNAL_REGION    Component VCS CH: Task in the video coding system where the coder detects address region of interest (ROI) elements on an image.\nINTERNAL_POSTCODE  Component VCS CH: Task in the video coding system where the coder enters the postcode based on an address region of interest (ROI) image.\nINTERNAL_ADDRESS   Component VCS CH: Task in the video coding system where the coder enters the recipient address based on an address region of interest (ROI) image.\nEXTERNAL_REGION    Component VCS Offshore: Task in the video coding system where the coder detects address region of interest (ROI) elements on an image.\nEXTERNAL_POSTCODE  Component VCS Offshore: Task in the video coding system where the coder enters the postcode based on an address region of interest (ROI) image.\nEXTERNAL_ADDRESS   Component VCS Offshore: Task in the video coding system where the coder enters the recipient address based on an address region of interest (ROI) image."
  VideoCodedTimeToLife:
    type: object
    properties:
      type:
        $ref: 'TimeToLifeType'
        description: "The maximum time and its priority define how long the coding request is supposed to take before it is coded. This information is recieved by SDS.\nIf SDS does not send this information, the platform will load the default setting when the mailpiece is received."
      amount:
        $ref: 'Int'
        description: 'Amount of time in miliseconds.'
    required:
      - type
      - amount
    additionalProperties: false
  VideoCodingResult:
    type: object
    properties:
      codingTask:
        $ref: 'VideoCodedCodingTask'
        description: 'The name of the coding task.'
      codingRequestType:
        $ref: 'VideoCodedCodingRequestType'
        description: 'The type of the coding request.'
      codingResultType:
        $ref: 'VideoCodedCodingResultType'
        description: 'The coding result type.'
      activities:
        type: array
        items:
          $ref: 'VideoCodedActivity'
        description: 'Activities the Coder or the Platforms performs during a coding requets.'
      timeToLife:
        type: array
        items:
          $ref: 'VideoCodedTimeToLife'
        description: 'The maximum time, in milliseconds, the coding request is supposed to take before it is coded.'
      keystrokes:
        type: string
        description: 'The keystrokes entered by the coder to code the coding request.'
    required:
      - codingTask
      - codingRequestType
      - codingResultType
      - keystrokes
    additionalProperties: false
    description: 'Information captured by the coding systems during coding'
  VideoEvents:
    type: object
    properties:
      sortingUnit:
        $ref: 'CodedSortingUnit'
        description: 'Sorting unit where the mailpiece was being processed.'
      serviceProvider:
        $ref: 'VideoServiceProvider'
        description: 'Service provider which coded the coding request.'
      codingResult:
        $ref: 'VideoCodingResult'
        description: 'Contains the coding results per coding request for a specific coding task.'
    required:
      - sortingUnit
      - serviceProvider
    additionalProperties: false
  VideoServiceProvider:
    type: object
    properties:
      name:
        type: string
        description: 'The name of the service provider which coded the coding request (e.g. SPS Vietnam).'
      location:
        type: string
        description: 'The name of the service provider location which coded the quality coding request.'
    required:
      - name
      - location
    additionalProperties: false
